### ISSUE TITLE
Scontistiche ignorate dal modulo

### ISSUE THREAD

**Issue by steno-baz** [fattureincloud/prestashop#1]
Sto integrando il modulo con prestashop (versione 1.7.8.7) e ho un problema con gli sconti standard dei prodotti quando importo gli ordini su fatture in cloud.

L'ordine viene regolarmente creato e tutti i campi sono corretti tranne per il prezzo di prodotti con uno sconto **IMPORTO**. Con gli sconti percentuale non c'è nessun problema.

Conosco poco fatture in cloud ma mi pare di vedere che lo sconto importo non è gestibile nella riga prodotto. E' possibile soltanto aggiungere una riga con importo negativo.

Tra le possibili soluzioni vedo:

- il modulo trasforma lo sconto importo in un valore percentuale (rischio decimali)
- il modulo invia il prezzo netto a fatture in cloud (meno rischioso ma lo sconto non è visibile nel documento)
- il modulo aggiunge una riga con importo negativo per il valore dello sconto (una riga ogni prodotto scontato?)

Sono disponibile a valutare insieme eventuali sviluppi.

**Comment by websuvius** [comment]
Grazie @steno-baz per la segnalazione.
Nella prossima release aggiungeremo una riga con importo negativo.
Saluti

**Comment by steno-baz** [comment]
Grazie per la risposta.

**Comment by websuvius** [comment]
Risolto nella release v2.1.0
