### ISSUE TITLE
Prezzi finali errati su Fatture in Cloud

### ISSUE THREAD

**Issue by Drakas** [fattureincloud/prestashop#2]
Buongiorno,
Sto collegando Prestashop utilizzando il plugin officiale per creare le fatture su Fatture in Cloud.
Noto il seguente problema di arrotondamento quando si applica lo sconto.

Ordine creato su Prestahop:
1xPRODOTTO TEST FATTURE, prezzo netto: 975,409836 con poi applicazione del 50% di sconto

Considerando l'IVA 22%, il totale finito lordo per prestashop è 595,00 € , valore corretto e questo è quello che si vorrebbe anche come valore finale sulla fattura di Fatture in Cloud, invece viene generata la Fattura con lordo uguale a 594,99 € . Il che è un problema dato che c'è quel centesimo.

Vedere il seguente URL dove c'è il follow-up che conferma che il plugin prestashop, ha bisogno di essere riscritto trasmettendo valori lordi e non netti come è ora, per avere il totale corretto trasmesso su fatture in cloud:

Link: https://github.com/fattureincloud/api/discussions/109

**Comment by websuvius** [comment]
Ciao. Grazie per la segnalazione.
Il problema è stato risolto con la release 2.1.5.
Chiudo.
