### ISSUE TITLE
Problema con integrazione

### ISSUE THREAD

**Issue by AndreaDev01** [fattureincloud/prestashop#3]
Buongiorno, sto provando a integrare il modulo con prestashop, ma non mi funziona lo scarico automatico prodotti dal magazzino, la sincronizzazione delle anagrafiche, e inoltre non riesco a capire come importare tutte le anagrafiche e i prodotti che ho su prestashop su fatture in cloud (O viceversa)

**Comment by valmoz** [comment]
Buongiorno,
le consiglio di seguire questa guida: [Integrazione Prestashop](https://help.fattureincloud.it/help/articolo/659-integrazione-prestashop-fic-app-store)

Nel caso in cui non dovesse essere sufficiente, le consiglio di contattare il [Supporto Clienti](https://developers.fattureincloud.it/docs/support) sulla pagina di Fatture in Cloud indicando:
- [Company ID](https://developers.fattureincloud.it/docs/basics/company-scoped-methods#-where-can-i-find-my-company_id)
- Eventuali errori che si verificano (più entra nel dettaglio più sarà semplice aiutarla)

Grazie 
Mauro
